Add QR Code Scanner
calblueprint/our-city-forest pull request #1
Opened 2024-10-05 20:07 UTC by adityapawar1

## What's new in this PR
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

### Screenshots
[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy! Use the provided image template. Drag the desired image into the PR, then copy the link into the placeholder."

[image placeholder]: <img src="place image link here!!!" width="240" height="540">

## How to review
[//]: # 'Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?'

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."

## Relevant links
### Online sources
[//]: # 'Copy links to any tutorials or documentation that was useful to you when working on this PR'

### Related PRs
[//]: # "Add related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @insert pl github username here

2024-10-19 01:58 UTC, AlexWang05 commented
LGTM 👍

2024-10-30 21:04 UTC, christophertorres1 requested changes
Amazing work! 

Just some minor changes to maintain consistency in the project's file structure, and remove extra comments except for function descriptions. 

Thanks Adi!!

2024-10-30 21:04 UTC, christophertorres1 commented on src/types.ts
> +// Not sure where to keep this stuff
Remove comments except short and precise ones for functions

2024-11-07 02:37 UTC, adityapawar1 commented
should be ready for review @christophertorres1

2024-11-13 08:18 UTC, christophertorres1 approved these changes

2024-11-13 08:32 UTC, merged