Lo-fi login pages with navigation
calblueprint/our-city-forest pull request #4
Opened 2024-10-18 01:39 UTC by carolynzhuang

## What's new in this PR
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."
Added basic login that leads you to the member login page (and guest login, which hasn't been created). 

### Screenshots
[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy! Use the provided image template. Drag the desired image into the PR, then copy the link into the placeholder."
![截屏 2024-10-17 18 37 32-1](https://github.com/user-attachments/assets/918a5962-0a30-47e4-aa5e-0437f79a54a9)
![截屏 2024-10-17 18 37 29](https://github.com/user-attachments/assets/c7b68282-4179-48f4-85b1-c271382ab694)

## How to review
[//]: # 'Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?'
press the button that leads you from login to member login to ensure it works

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."

## Relevant links
### Online sources
[//]: # 'Copy links to any tutorials or documentation that was useful to you when working on this PR'

### Related PRs
[//]: # "Add related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @christophertorres1

2024-10-25 05:53 UTC, katyhonguyen commented
looks good to me, the code is clean!

2024-10-30 21:28 UTC, christophertorres1 requested changes
A few naming edits to ensure consistency throughout the project. Great job overall Carolyn!!

2024-10-30 21:28 UTC, christophertorres1 commented on src/navigation/types.tsx
Rename the folder 'navigation' to 'types', and the file 'types.tsx' to 'types.ts'

2024-10-30 21:28 UTC, christophertorres1 commented on src/components/Login.tsx
> +          <Text style={styles.buttonText}>Staff or Member</Text>
Change "Staff or Member" to "Admin"

2024-10-30 21:28 UTC, christophertorres1 commented on src/screens/MemberLoginScreen.tsx
> +      <Text style={styles.loginHeadingText}>Staff and Member Login</Text>
Change to "Admin Login"

2024-11-13 08:51 UTC, christophertorres1 approved these changes

2024-11-13 09:49 UTC, merged