Katynguyen/ocf 11 lo fi contact page
calblueprint/our-city-forest pull request #5
Opened 2024-10-19 02:25 UTC by katyhonguyen

## What's new in this PR
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

Contact page lofi, haven't implemented the icons

### Screenshots
[//]: # "Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy! Use the provided image template. Drag the desired image into the PR, then copy the link into the placeholder."

[image placeholder]: <img src="place image link here!!!" width="240" height="540">

(cant submit image rn but will update)

## How to review
[//]: # 'Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?'

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."

## Relevant links
### Online sources
[//]: # 'Copy links to any tutorials or documentation that was useful to you when working on this PR'

### Related PRs
[//]: # "Add related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @insert pl github username here

2024-10-19 19:12 UTC, carolynzhuang commented on styles.ts
> +    marginBottom: 50,
I think it's better to try to avoid using margins on text

2024-10-19 19:13 UTC, carolynzhuang commented on styles.ts
> +    height: width * (8 / 9),
Maybe use aspect ratio here?

2024-10-19 19:16 UTC, carolynzhuang commented on styles.ts
> +    position: 'absolute',
Using absolute positioning might not show up well on different screen sizes

2024-10-19 19:25 UTC, carolynzhuang commented on styles.ts
> +  Heading4: {
I feel like this name could be more descriptive

2024-10-19 19:26 UTC, carolynzhuang commented on App.tsx
i think this will eventually be moved to contactPage in pages?

2024-10-19 19:27 UTC, carolynzhuang commented on styles.ts
move to src/pages

2024-10-19 19:27 UTC, carolynzhuang commented on styles.ts
> +  Heading4: {
This name could be more descriptive

2024-10-19 19:27 UTC, carolynzhuang commented on styles.ts
> +    height: width * (8 / 9),
Maybe use aspect ratio here?

2024-10-19 19:28 UTC, carolynzhuang commented on styles.ts
> +    position: 'absolute',
Absolute positioning might not show up well on different screen sizes

2024-10-19 19:29 UTC, carolynzhuang commented on styles.ts
> +    marginBottom: 10,
change to padding

2024-10-30 21:07 UTC, christophertorres1 requested changes
Minor change for file structure consistency. Update to the current design and ignore further changes made to the contact screen for now. Wonderful job Katy!

2024-12-02 07:12 UTC, christophertorres1 approved these changes

2024-12-02 07:13 UTC, merged